model:
  name: torchvision.models.resnet50

dataset:
  name: torchvision.datasets.CIFAR10

transforms:
- name: torchvision.transforms.CenterCrop
  size: 10
- name: torchvision.transforms.RandomVerticalFlip
  p: 0.5
